# Generated by Django 3.2.3 on 2021-05-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduler',
            old_name='end_time',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='scheduler',
            old_name='start_time',
            new_name='startDate',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='date',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='info',
        ),
        migrations.AddField(
            model_name='scheduler',
            name='notes',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
