# Generated by Django 3.2.3 on 2021-05-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('others', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.CharField(choices=[('무통장 입금', '무통장 입금')], max_length=10)),
                ('paid_amount', models.IntegerField()),
                ('is_complete', models.BooleanField(default=False, verbose_name='예매 완료 여부')),
            ],
        ),
    ]
