# Generated by Django 3.2.3 on 2021-05-15 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='compainion',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='예약자'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='specific_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_content', to='contents.specificcontent', verbose_name='예매 컨텐츠 정보'),
        ),
    ]
