# Generated by Django 3.2.3 on 2021-05-21 01:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0003_rename_compainion_reservation_companion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='companion',
            field=models.ManyToManyField(blank=True, related_name='companion', to=settings.AUTH_USER_MODEL),
        ),
    ]
