# Generated by Django 3.2.3 on 2021-05-15 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('DISPLAY', '전시회'), ('MOVIE', '영화')], max_length=10)),
                ('cast', models.CharField(blank=True, max_length=30, null=True)),
                ('director', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(max_length=10)),
                ('plot', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecificContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.content')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=3)),
                ('seat_type', models.CharField(choices=[('', 'Select'), ('VIP', 'VIP'), ('R', 'R'), ('S', 'S'), ('A', 'A')], max_length=5)),
                ('is_reserved', models.BooleanField()),
                ('specific_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.specificcontent')),
            ],
            options={
                'unique_together': {('seat_number', 'specific_content')},
            },
        ),
    ]
