# Generated by Django 3.2.3 on 2021-05-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='genre',
            field=models.CharField(choices=[('EXHIBITION', '전시회'), ('LECTURE', '강연'), ('CONCERT', '영화'), ('CULTURE_EVENT', '문화행사'), ('SPORTS', '스포츠')], max_length=20),
        ),
    ]
