# Generated by Django 3.2.3 on 2021-05-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_alter_content_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='preference_one',
            field=models.CharField(choices=[('유쾌한', '유쾌한'), ('감동적인', '감동적인'), ('스릴있는', '스릴있는'), ('어두운', '어두운'), ('힐링', '힐링'), ('설레는', '설레는'), ('잔잔한', '잔잔한'), ('역동적인', '역동적인'), ('유익한', '유익한'), ('사진 찍기 좋은', '사진 찍기 좋은'), ('장르물', '장르물'), ('온택트', '온택트')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='preference_two',
            field=models.CharField(choices=[('유쾌한', '유쾌한'), ('감동적인', '감동적인'), ('스릴있는', '스릴있는'), ('어두운', '어두운'), ('힐링', '힐링'), ('설레는', '설레는'), ('잔잔한', '잔잔한'), ('역동적인', '역동적인'), ('유익한', '유익한'), ('사진 찍기 좋은', '사진 찍기 좋은'), ('장르물', '장르물'), ('온택트', '온택트')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='genre',
            field=models.CharField(choices=[('EXHIBITION', '전시'), ('LECTURE', '강연'), ('CONCERT', '공연예술'), ('CULTURE_EVENT', '문화행사'), ('SPORTS', '스포츠')], max_length=20),
        ),
    ]
